### PR TITLE
Yolox load master map unit test

### PR DESCRIPTION
**Pull request by ongtw**
Added outstanding unit test for YoloX to test loading of master map file.

### CODE REVIEW

**Review by liyier90 — COMMENTED** [review]
The other functions at L91, L100, L109, L120, and L140 are only tested on `model.yolo`. Is it necessary to also implement those tests for `model.yolox`?

If it's necessary, consider using a fixture that gives `model.yolo` and `model.yolox` instead of just duplicating the tests. I think using a fixture for these 2 models is also consistent with how they share the same `map_yolo` key in the `master_mapping.yml`.

**Comment by ongtw** [comment]
> The other functions at L91, L100, L109, L120, and L140 are only tested on `model.yolo`. Is it necessary to also implement those tests for `model.yolox`?
> 
> If it's necessary, consider using a fixture that gives `model.yolo` and `model.yolox` instead of just duplicating the tests. I think using a fixture for these 2 models is also consistent with how they share the same `map_yolo` key in the `master_mapping.yml`.

I think there is no need because of the following reason:

The diagram below shows the added "Translation Layer" that converts class name to object ID and reads each object detection model's mapping system.
The unit tests are designed to test this translation layer, not model operation (which are handled by another set of unit tests).
The red tests check that each of the 3 model's mapping system is loaded correctly: here we need to test all 3 models.
The blue tests check for different translation cases: but they need a model to run and Yolo was just chosen out of the 3.
We could duplicate the blue tests for YoloX (and EfficientDet) but then we would just be testing the translation layer 2 (or 3) times.

UnitTest

**Comment by ongtw** [comment]
Maybe the blue test names create some doubts due to the "yolo" within them. I could remove "yolo" from the test names, to have just `test_config_loader_change_class_name_to_id_all_text`, etc...
Perhaps this would be clearer?

**Comment by liyier90** [comment]
I see, it's much clearer now, thanks for the explanation. Perhaps just a comment or docstring somewhere to explicitly mention that those tests don't have to be repeated for `efficientdet` and `yolox`.

Because it initially looked like missed test cases/branches with `efficientdet`, `yolo`, and `yolox` tested above but only `yolo` tested below.

**Comment by ongtw** [comment]
Updated unit test code with comments/docstrings to explain what is being tested and removed `yolo` from some test names to avoid confusion.

**Review by liyier90 — APPROVED** [review]

**Pull request merged**
